spring:
  profiles:
    active: native
  application:
    name: config-server
  cloud:
    config:
      server:
        native:
          searchLocations: "classpath:/config-repo"
server:
  port: 8889
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka