spring:
  application:
    name: customer
  zipkin:
    base-url: http://localhost:9411
server:
  port: 8080
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka
resilience4j:
  circuitbreaker:
    instances:
      inventory-service:
        failureRateThreshold: 30
        minimumNumberOfCalls: 3
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 3
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 1